
package com.ithema.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.ithema.service.ObjectFactory;
import com.ithema.service.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://service.ithema.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://service.ithema.com/", className = "com.ithema.service.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.ithema.com/", className = "com.ithema.service.SaveResponse")
    public void save(
            @WebParam(name = "arg0", targetNamespace = "")
                    User arg0);

}
